<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    public function run()
    {
        DB::table('productos')->insert([
            [
                'codigo' => 'A001',
                'nombre_producto' => 'Arroz Superior 5kg',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 18.50,
                'precio_mayorista' => 17.00,
                'descuento' => 1.50,
                'stock_disponible' => 100,
                'descripcion' => 'Arroz de grano largo y extra seleccionado.',
                'presentacion' => 'Saco 5kg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A002',
                'nombre_producto' => 'Azúcar Rubia 2kg',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 8.00,
                'precio_mayorista' => 7.50,
                'descuento' => 0.50,
                'stock_disponible' => 80,
                'descripcion' => 'Azúcar rubia natural sin refinar.',
                'presentacion' => 'Bolsa 2kg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A003',
                'nombre_producto' => 'Harina de Trigo 1kg',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 6.50,
                'precio_mayorista' => 6.00,
                'descuento' => 0.50,
                'stock_disponible' => 120,
                'descripcion' => 'Harina de trigo fortificada de alta calidad.',
                'presentacion' => 'Paquete 1kg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A004',
                'nombre_producto' => 'Fideos Tallarín 500g',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 4.00,
                'precio_mayorista' => 3.50,
                'descuento' => 0.50,
                'stock_disponible' => 150,
                'descripcion' => 'Fideos de sémola de trigo enriquecidos.',
                'presentacion' => 'Bolsa 500g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A005',
                'nombre_producto' => 'Leche Evaporada 400ml',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 4.50,
                'precio_mayorista' => 4.00,
                'descuento' => 0.50,
                'stock_disponible' => 200,
                'descripcion' => 'Leche evaporada entera de alta calidad.',
                'presentacion' => 'Lata 400ml',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A006',
                'nombre_producto' => 'Aceite Vegetal 1L',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 12.00,
                'precio_mayorista' => 11.00,
                'descuento' => 1.00,
                'stock_disponible' => 90,
                'descripcion' => 'Aceite vegetal refinado, ideal para cocinar.',
                'presentacion' => 'Botella 1L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A007',
                'nombre_producto' => 'Sal Yodada 1kg',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 2.50,
                'precio_mayorista' => 2.00,
                'descuento' => 0.50,
                'stock_disponible' => 300,
                'descripcion' => 'Sal yodada de alta pureza.',
                'presentacion' => 'Bolsa 1kg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A008',
                'nombre_producto' => 'Café Instantáneo 200g',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 25.00,
                'precio_mayorista' => 22.50,
                'descuento' => 2.50,
                'stock_disponible' => 60,
                'descripcion' => 'Café soluble de aroma intenso.',
                'presentacion' => 'Frasco 200g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A009',
                'nombre_producto' => 'Chocolate en Polvo 250g',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 15.00,
                'precio_mayorista' => 13.50,
                'descuento' => 1.50,
                'stock_disponible' => 70,
                'descripcion' => 'Chocolate en polvo para bebidas y repostería.',
                'presentacion' => 'Lata 250g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A010',
                'nombre_producto' => 'Galletas de Avena 400g',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 8.00,
                'precio_mayorista' => 7.00,
                'descuento' => 1.00,
                'stock_disponible' => 110,
                'descripcion' => 'Galletas de avena con miel y almendras.',
                'presentacion' => 'Paquete 400g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Agregamos más productos...
            [
                'codigo' => 'A011',
                'nombre_producto' => 'Lenteja Amarilla 1kg',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 7.00,
                'precio_mayorista' => 6.50,
                'descuento' => 0.50,
                'stock_disponible' => 95,
                'descripcion' => 'Lentejas amarillas seleccionadas.',
                'presentacion' => 'Bolsa 1kg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A012',
                'nombre_producto' => 'Frijol Canario 1kg',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 9.50,
                'precio_mayorista' => 9.00,
                'descuento' => 0.50,
                'stock_disponible' => 100,
                'descripcion' => 'Frijol canario suave y nutritivo.',
                'presentacion' => 'Bolsa 1kg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'A013',
                'nombre_producto' => 'Mermelada de Fresa 450g',
                'categoria' => 'Abarrotes',
                'precio_unitario' => 10.00,
                'precio_mayorista' => 9.00,
                'descuento' => 1.00,
                'stock_disponible' => 85,
                'descripcion' => 'Mermelada natural de fresa sin conservantes.',
                'presentacion' => 'Frasco 450g',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
